
# Environment variables to set: "host", "key"

############################################################
# Global endpoints
############################################################

### Verify API key
GET     {{host}}/api/verifykey
Authorization: {{key}}

### Get list of public tabs
GET     {{host}}/api/tabs

### Get list of tabs
GET     {{host}}/api/tabs
Authorization: {{key}}

############################################################
# Tab-level endpoints
############################################################

@tabid = 2

### Get tab
GET     {{host}}/api/tab
          ?id={{tabid}}
Authorization: {{key}}

### Get all teams on tab
GET     {{host}}/api/tab/teams
          ?id={{tabid}}
Authorization: {{key}}

### Get all delegations on tab
GET     {{host}}/api/tab/delegations
          ?id={{tabid}}
Authorization: {{key}}

### Get all speakers on tab
GET     {{host}}/api/tab/speakers
          ?id={{tabid}}
Authorization: {{key}}

### Get all judges on tab
GET     {{host}}/api/tab/judges
          ?id={{tabid}}
Authorization: {{key}}

### Get all rounds on tab
GET     {{host}}/api/tab/rounds
          ?id={{tabid}}
Authorization: {{key}}


### Get random pairings
GET     {{host}}/api/tab/generate-pairings/random
          ?id={{tabid}}
Authorization: {{key}}

############################################################
# Team-level endpoints
############################################################

@teamid = 108

### Get team
GET     {{host}}/api/team
          ?id={{teamid}}
Authorization: {{key}}

### Create team
POST    {{host}}/api/team
Content-Type: application/x-www-form-urlencoded
Authorization: {{key}}

tabid={{tabid}}
&name=Mordor A
&delegation=Mordor
&status=2

### Delete team
DELETE  {{host}}/api/team
          ?id={{teamid}}
Authorization: {{key}}

### Update team
PATCH   {{host}}/api/team
          ?id={{teamid}}
Content-Type: application/x-www-form-urlencoded
Authorization: {{key}}

name=Mordor 1
&delegation=Mordor
&status=3

### Toggle team
PATCH   {{host}}/api/team/toggle
          ?id={{teamid}}
Authorization: {{key}}

### Get speakers on team
GET     {{host}}/api/team/speakers
          ?id={{teamid}}
Authorization: {{key}}

############################################################
# Speaker-level endpoints
############################################################

@speakerid = 74

### Get speaker
GET     {{host}}/api/speaker
          ?id={{speakerid}}
Authorization: {{key}}

### Create speaker
POST    {{host}}/api/speaker
Content-Type: application/x-www-form-urlencoded
Authorization: {{key}}

teamid={{teamid}}
&firstname=Sauron
&lastname=Gorthaur
&status=3

### Delete speaker
DELETE  {{host}}/api/speaker
          ?id={{speakerid}}
Authorization: {{key}}

### Update speaker
PATCH   {{host}}/api/speaker
          ?id={{speakerid}}
Content-Type: application/x-www-form-urlencoded
Authorization: {{key}}

firstname=Some
&lastname=Dude
&status=1

############################################################
# Judge-level endpoints
############################################################

@judgeid = 6

### Get judge
GET     {{host}}/api/judge
          ?id={{judgeid}}
Authorization: {{key}}

### Register judge
POST    {{host}}/api/judge
Content-Type: application/x-www-form-urlencoded
Authorization: {{key}}

tabid={{tabid}}
&firstname=English
&lastname=Teacher
&rating=3

### Delete judge
DELETE  {{host}}/api/judge
          ?id={{judgeid}}
Authorization: {{key}}


### Update judge
PATCH   {{host}}/api/judge
          ?id={{judgeid}}
Content-Type: application/x-www-form-urlencoded
Authorization: {{key}}

firstname=Good
&lastname=Judge
&rating=7

### Toggle judge
PATCH   {{host}}/api/judge/toggle
          ?id={{judgeid}}
Authorization: {{key}}

### Get clashes for judge
GET     {{host}}/api/judge/clashes
          ?id={{judgeid}}
Authorization: {{key}}

### Set clash
POST    {{host}}/api/judge/clash
          ?judgeid={{judgeid}}
          &teamid={{teamid}}
          &level=10
Authorization: {{key}}

### Unset clash
DELETE  {{host}}/api/judge/clash
          ?judgeid={{judgeid}}
          &teamid={{teamid}}
Authorization: {{key}}

############################################################
# Round-level endpoints
############################################################

@roundnumber = 1

### Get round
GET     {{host}}/api/round
          ?tabid={{tabid}}
          &roundnumber={{roundnumber}}
Authorization: {{key}}

### Add round
POST    {{host}}/api/round
          ?tabid={{tabid}}
Authorization: {{key}}

### Delete round
DELETE  {{host}}/api/round
          ?tabid={{tabid}}
          &roundnumber={{roundnumber}}
Authorization: {{key}}

### Lock round
PATCH   {{host}}/api/round/lock
          ?tabid={{tabid}}
          &roundnumber={{roundnumber}}
Authorization: {{key}}

### Unlock round
PATCH   {{host}}/api/round/unlock
          ?tabid={{tabid}}
          &roundnumber={{roundnumber}}
Authorization: {{key}}
