###
POST {{host}}/auth/sign-in HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "password"
}
###
GET {{host}}/auth/verifykey HTTP/1.1
Authorization: {{key}}
###
POST {{host}}/auth/sign-out HTTP/1.1
Authorization: 
