@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODk1NTE4MTUsImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUudGxkIiwiaXNBZG1pbiI6dHJ1ZX0.i00DlWgCJStkJFsPtiCd0udcH-7pcjBZWp0UByneqOo
###
GET http://localhost:8080/token/verify
Authorization: Bearer {{token}}
###
GET http://localhost:8080/tab
###
GET http://localhost:8080/tab
Authorization: Bearer {{token}}
###
GET http://localhost:8080/tab/1
###
GET http://localhost:8080/tab/2
###
GET http://localhost:8080/tab/3
Authorization: Bearer {{token}}
###
POST http://localhost:8080/tab
###
POST http://localhost:8080/tab
Authorization: Bearer {{token}}

{
  "name": "New public tab",
  "isPublic": true
}
###
DELETE http://localhost:8080/tab/4
###
DELETE http://localhost:8080/tab/3
Authorization: Bearer {{token}}
###
PATCH http://localhost:8080/tab/3
Authorization: Bearer {{token}}

{
  "name": "Renamed new public tab"
}
